todo/urls.py
from django.conf.urls import url
from django.contrib import admin


from .views import (
	index,
	addTodo,
	completeTodo,
	deleteCompleted,
	deleteAll,
	)

urlpatterns = [
	url(r'^$', index, name = 'index'),
	url(r'^add/$', addTodo, name = 'add' ),
	url(r'^complete/(?P<todo_id>\d+)/$', completeTodo, name = 'complete'),
	url(r'^deletecomplete/$', deleteCompleted, name = 'deletecomplete' ),
	url(r'^deleteall/$', deleteAll, name = 'deleteall' ),

]

todoapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('todo.urls', namespace = 'todo')),
]

todo/models.py
from django.db import models

#Task model.
class Todo(models.Model):
	text = models.CharField(max_length=40)
	complete = models.BooleanField(default=False)

	def __str__(self):
		return self.text

todo/forms.py
from django import forms


class TodoForm(forms.Form):
	text = forms.CharField(
		max_length=40, 
		widget = forms.TextInput( attrs = {'class' : 'form-control', 'placeholder' : 'Enter todo e.g. Delete junk files', 'aria-label' : 'Todo', 'aria-describedby' : 'add-btn'})
		)

todo/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .models import Todo
from .forms import TodoForm


# View for listing all the tasks.
def index(request):
	todo_list = Todo.objects.order_by('id')
	form = TodoForm()
	context = {'todo_list': todo_list, 'form': form}
	return render(request, 'index.html', context)

@require_POST #view for add a new task
def addTodo(request):
	form = TodoForm(request.POST)

	if form.is_valid(): #form is the space to write the task
		new_todo = Todo(text=request.POST['text'])
		new_todo.save()

	return redirect('todo:index')

def completeTodo(request, todo_id): #  sets the taks as completed
	todo = Todo.objects.get(pk = todo_id)
	todo.complete = True
	todo.save()

	return redirect('todo:index')

def deleteCompleted(request):#  view  to delete the completed todos
	Todo.objects.filter(complete__exact=True).delete()
	return redirect('todo:index')


def deleteAll(request): # view to delete all the elements.
	Todo.objects.all().delete()

	return redirect('todo:index')

todo/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>ToDo App</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'todo/bs/css/flatly.min.css' %}" />
		<link rel="stylesheet" href="{% static 'todo/styles.css' %}" />

		
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row">
				<div class="col-lg-4 col-lg-offset-4" id="content">
					<h2>ADD YOUR TO DO LIST BELOW</h2>
					
					<form action= "{% url 'todo:add' %}" method="POST" role="form">
						{% csrf_token %}
						
						<div class="form-group">
							<div class="input-group">
							  
							  {{ form.text }}
							  <span class="input-group-btn">
								  <button type="submit" class="btn btn-default" id="add-btn">ADD</button>
							  </span>
							</div>
						</div>
					</form>

					<div class="row t10">
						<div class="col-lg-12">
							<div class="btn-toolbar">
								<div class="btn-group">
									<a href="{% url 'todo:deletecomplete' %}">
									<button type="button" class="btn btn-warning">
										<i class="glyphicon glyphicon-trash"></i> DELETE COMPLETED
									</button>
								</div>
								<div class="btn-group">
									<a href="{% url 'todo:deleteall' %}">
									<button type="button" class="btn btn-warning">
										<i class="glyphicon glyphicon-trash"></i> DELETE ALL
									</button>
								</div>
							</div>
						</div>
					</div>

					<ul class="list-group t20">
					
					<!--For loop for todo list --> 

						{% for todo in todo_list %}							
							{% if todo.complete %} <!-- list of the complete todos -->
													
							<li class="list-group-item todo-completed">{{ todo.text }} <span class = "glyphicon glyphicon-ok"></span></li>
							
							{% else %} <!-- List of the uncomplete todos-->

							<a href= "/complete/{{ todo.id }}/" ><li class="list-group-item">{{ todo.text }} </span></li></a>
							
							{% endif %}
						
						{% endfor %}	

					</ul>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						 <strong>Todo App</strong>
					</div>
				</div>
			</footer>
		</div>
		
	</body>
</html>